import { StyleSheet } from "react-native";
import {
  moderateScale,
  normalizeFont,
  scale,
  verticalScale,
} from "../../../lib/responsive";
import { colors } from "../../../theme/colors";

export const chatGuardianStyles = StyleSheet.create({
  chatGuardianBoard: {
    flexDirection: "row",
    gap: moderateScale(12),
    minHeight: verticalScale(420),
  },
  chatGuardianBoardPhone: {
    flexDirection: "column",
    minHeight: verticalScale(520),
  },
  chatGuardianContactsPanel: {
    flex: 0.36,
    borderRadius: scale(18),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: moderateScale(14),
    gap: moderateScale(12),
  },
  chatGuardianContactsPanelPhone: {
    flex: 0,
    width: "100%",
  },
  chatGuardianPanelEyebrow: {
    color: colors.text,
    fontSize: normalizeFont(11),
    fontWeight: "800",
    letterSpacing: moderateScale(0.4),
    textTransform: "uppercase",
  },
  chatGuardianContactsList: {
    gap: moderateScale(10),
  },
  chatGuardianContactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(10),
    borderRadius: scale(16),
    borderWidth: scale(2),
    borderColor: "#e5e7eb",
    padding: moderateScale(10),
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  chatGuardianContactRowPhone: {
    minHeight: verticalScale(66),
    padding: moderateScale(12),
  },
  chatGuardianContactRowActive: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: "#dbeafe",
    shadowColor: colors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  chatGuardianContactAvatarWrap: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(999),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: "#d1d5db",
  },
  chatGuardianContactAvatar: {
    fontSize: normalizeFont(18),
  },
  chatGuardianContactTextWrap: {
    flex: 1,
    gap: moderateScale(2),
  },
  chatGuardianContactName: {
    color: colors.textSecondary,
    fontSize: normalizeFont(14),
    fontWeight: "800",
  },
  chatGuardianContactSubtitle: {
    color: colors.textSecondary,
    fontSize: normalizeFont(11),
    fontWeight: "600",
  },
  chatGuardianThreatDot: {
    width: scale(12),
    height: scale(12),
    borderRadius: scale(999),
    borderWidth: scale(2),
    borderColor: "#ffffff",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  chatGuardianThreatSafe: {
    backgroundColor: "#22c55e",
  },
  chatGuardianThreatWarning: {
    backgroundColor: "#f59e0b",
  },
  chatGuardianThreatDanger: {
    backgroundColor: "#ef4444",
  },
  chatGuardianChatPanel: {
    flex: 1,
    borderRadius: scale(18),
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    overflow: "hidden",
  },
  chatGuardianHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: moderateScale(12),
    padding: moderateScale(14),
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.35)",
    backgroundColor: colors.surface,
  },
  chatGuardianHeaderPhone: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  chatGuardianHeaderTextWrap: {
    flex: 1,
    gap: 4,
  },
  chatGuardianHeadline: {
    color: colors.text,
    fontSize: normalizeFont(18),
    fontWeight: "800",
  },
  chatGuardianIntro: {
    color: colors.textMuted,
    fontSize: normalizeFont(13),
    lineHeight: verticalScale(20),
    fontWeight: "600",
  },
  chatGuardianThreatChip: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "#6366f1",
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(6),
    borderWidth: scale(2),
    borderColor: "#4f46e5",
    shadowColor: "#6366f1",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  chatGuardianThreatChipText: {
    color: "#ffffff",
    fontSize: normalizeFont(11),
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  chatGuardianThread: {
    padding: 14,
    gap: moderateScale(10),
    minHeight: verticalScale(240),
    backgroundColor: "linear-gradient(180deg, #fafafa 0%, #ffffff 100%)",
  },
  chatGuardianMessageBubble: {
    maxWidth: "86%",
    borderRadius: scale(18),
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(10),
    gap: 4,
  },
  chatGuardianMessageIncoming: {
    alignSelf: "flex-start",
    backgroundColor: "#dbeafe",
    borderTopLeftRadius: 6,
  },
  chatGuardianMessageOutgoing: {
    alignSelf: "flex-end",
    backgroundColor: "#e0f2fe",
    borderTopRightRadius: 6,
  },
  chatGuardianMessageSender: {
    color: "#1e293b",
    fontSize: normalizeFont(11),
    fontWeight: "800",
  },
  chatGuardianMessageText: {
    color: "#0f172a",
    fontSize: normalizeFont(15),
    lineHeight: verticalScale(22),
    fontWeight: "600",
  },
  chatGuardianMessageTime: {
    color: "#64748b",
    fontSize: normalizeFont(10),
    fontWeight: "700",
  },
  chatGuardianAlertBox: {
    marginHorizontal: moderateScale(14),
    marginBottom: moderateScale(12),
    borderRadius: scale(14),
    borderWidth: scale(2),
    borderStyle: "solid",
    borderColor: "#f59e0b",
    backgroundColor: "#fef3c7",
    padding: moderateScale(12),
    gap: moderateScale(6),
    shadowColor: "#f59e0b",
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  chatGuardianAlertTitle: {
    color: "#78350f",
    fontSize: normalizeFont(13),
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  chatGuardianAlertList: {
    gap: moderateScale(4),
  },
  chatGuardianAlertItem: {
    color: "#b45309",
    fontSize: normalizeFont(12),
    lineHeight: verticalScale(18),
    fontWeight: "700",
  },
  chatGuardianActionPrompt: {
    marginHorizontal: moderateScale(14),
    color: colors.text,
    fontSize: normalizeFont(13),
    fontWeight: "800",
    letterSpacing: moderateScale(0.2),
  },
  chatGuardianActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: moderateScale(10),
    paddingHorizontal: moderateScale(14),
    paddingBottom: moderateScale(14),
  },
  chatGuardianActionButton: {
    flexBasis: "48%",
    minWidth: scale(140),
    borderRadius: scale(18),
    borderWidth: scale(2),
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(10),
    gap: 4,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  chatGuardianActionButtonPhone: {
    flexBasis: "100%",
    minWidth: "100%",
    minHeight: verticalScale(78),
    justifyContent: "center",
  },
  chatGuardianActionButtonSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: "#dbeafe",
    shadowColor: colors.accent,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionButtonCorrect: {
    borderColor: "#22c55e",
    borderWidth: 3,
    backgroundColor: "#dcfce7",
    shadowColor: "#22c55e",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionButtonWrong: {
    borderColor: "#ef4444",
    borderWidth: 3,
    backgroundColor: "#fee2e2",
    shadowColor: "#ef4444",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionIcon: {
    fontSize: normalizeFont(18),
  },
  chatGuardianActionTitle: {
    color: "#1f2937",
    fontSize: normalizeFont(14),
    fontWeight: "800",
    textAlign: "center",
    lineHeight: verticalScale(20),
  },
  chatGuardianActionTitleSelected: {
    color: "#0369a1",
    fontWeight: "900",
  },
  chatGuardianActionHint: {
    color: "#6b7280",
    fontSize: normalizeFont(12),
    fontWeight: "700",
    textAlign: "center",
  },
  chatGuardianActionHintSelected: {
    color: "#0284c7",
    fontWeight: "800",
  },
  chatGuardianTypingBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#dbeafe",
    borderTopLeftRadius: 6,
    maxWidth: "86%",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatGuardianTypingDot: {
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    backgroundColor: "#0369a1",
    marginHorizontal: 2,
  },
});
