import { StyleSheet } from "react-native";
import {
  moderateScale,
  normalizeFont,
  scale,
  verticalScale,
} from "../../../lib/responsive";
import { colors } from "../../../theme/colors";

export const firewallStyles = StyleSheet.create({
  firewallBoard: {
    flexDirection: "row",
    gap: moderateScale(12),
    userSelect: "none",
  },
  firewallBoardStacked: {
    flexDirection: "column",
  },
  firewallMainPanel: {
    flex: 1,
    gap: moderateScale(10),
    userSelect: "none",
  },
  firewallTopbar: {
    borderRadius: scale(14),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: moderateScale(10),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: moderateScale(10),
    userSelect: "none",
  },
  firewallTopbarCompact: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: moderateScale(12),
    padding: moderateScale(12),
  },
  firewallStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: moderateScale(10),
    alignItems: "center",
    flex: 1,
  },
  firewallStatsRowCompact: {
    gap: moderateScale(12),
  },
  firewallActionsRow: {
    flexDirection: "row",
    gap: moderateScale(8),
  },
  firewallActionsRowCompact: {
    justifyContent: "space-between",
    gap: moderateScale(10),
  },
  firewallStat: {
    color: colors.text,
    fontSize: normalizeFont(14),
    fontWeight: "700",
  },
  firewallShieldWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(6),
  },
  firewallShieldTrack: {
    width: scale(110),
    height: verticalScale(10),
    borderRadius: scale(999),
    backgroundColor: "#d1d5db",
    overflow: "hidden",
  },
  firewallShieldFill: {
    height: "100%",
    backgroundColor: "#22c55e",
  },
  firewallShieldText: {
    color: colors.text,
    fontSize: normalizeFont(12),
    fontWeight: "800",
  },
  firewallArena: {
    position: "relative",
    overflow: "hidden",
    borderRadius: scale(14),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: "#f0f9ff",
    minHeight: verticalScale(500),
    padding: moderateScale(12),
    userSelect: "none",
    shadowColor: "#0ea5e9",
    shadowOpacity: 0.08,
    shadowRadius: moderateScale(12),
    shadowOffset: { width: 0, height: moderateScale(4) },
    elevation: 2,
  },
  firewallArenaGlow: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(148, 163, 184, 0.05)",
  },
  firewallStar: {
    position: "absolute",
    borderRadius: scale(999),
    backgroundColor: "#ffffff",
  },
  firewallBubble: {
    width: scale(56),
    height: scale(56),
    borderRadius: scale(999),
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    position: "absolute",
  },
  firewallThreatBubble: {
    backgroundColor: "#fee2e2",
    borderWidth: scale(2),
    borderColor: "#ef4444",
    padding: moderateScale(12),
    shadowColor: "#dc2626",
    shadowOpacity: 0.15,
    shadowRadius: moderateScale(8),
    shadowOffset: { width: 0, height: moderateScale(2) },
    elevation: 3,
  },
  firewallDataBubble: {
    backgroundColor: "#dbeafe",
    borderWidth: scale(2),
    borderColor: "#3b82f6",
    marginTop: moderateScale(18),
    shadowColor: "#0284c7",
    shadowOpacity: 0.12,
    shadowRadius: moderateScale(6),
    shadowOffset: { width: 0, height: moderateScale(2) },
    elevation: 2,
  },
  firewallPowerBubble: {
    backgroundColor: "#fef3c7",
    borderWidth: scale(2),
    borderColor: "#f59e0b",
    marginTop: moderateScale(18),
    shadowColor: "#d97706",
    shadowOpacity: 0.12,
    shadowRadius: moderateScale(6),
    shadowOffset: { width: 0, height: moderateScale(2) },
    elevation: 2,
  },
  firewallBubbleIcon: {
    fontSize: normalizeFont(24),
  },
  firewallBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: moderateScale(10),
  },
  firewallPirateCard: {
    position: "absolute",
    borderRadius: scale(14),
    backgroundColor: "#ec4899",
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(10),
    minWidth: scale(170),
    shadowColor: "#be185d",
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(10),
    shadowOffset: { width: 0, height: moderateScale(4) },
    elevation: 5,
    userSelect: "none",
  },
  firewallPirateTitle: {
    color: "#ffffff",
    fontSize: normalizeFont(17),
    fontWeight: "800",
  },
  firewallPirateText: {
    color: "#fdf2f8",
    fontSize: normalizeFont(12),
    marginTop: moderateScale(2),
    fontWeight: "700",
  },
  firewallCoffreCard: {
    position: "absolute",
    bottom: moderateScale(14),
    width: scale(120),
    borderRadius: scale(999),
    backgroundColor: "#3b82f6",
    paddingHorizontal: moderateScale(18),
    paddingVertical: moderateScale(10),
    alignItems: "center",
    zIndex: 3,
    shadowColor: "#1e40af",
    shadowOpacity: 0.25,
    shadowRadius: moderateScale(12),
    shadowOffset: { width: 0, height: moderateScale(4) },
    elevation: 5,
    userSelect: "none",
  },
  firewallCoffreTitle: {
    color: "#ffffff",
    fontSize: normalizeFont(16),
    fontWeight: "800",
  },
  firewallCoffreHint: {
    color: "#dbeafe",
    fontSize: normalizeFont(11),
    fontWeight: "700",
    marginTop: moderateScale(2),
  },
  firewallQuestionCard: {
    borderRadius: scale(14),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: moderateScale(12),
    gap: moderateScale(10),
  },
  firewallQuestionModule: {
    color: colors.textMuted,
    fontSize: normalizeFont(12),
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: moderateScale(0.4),
  },
  firewallQuestionPrompt: {
    color: colors.text,
    fontSize: normalizeFont(18),
    lineHeight: verticalScale(25),
    fontWeight: "800",
  },
  firewallControlsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: moderateScale(8),
  },
  firewallControlButton: {
    borderRadius: scale(999),
    borderWidth: scale(1),
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: moderateScale(14),
    paddingVertical: moderateScale(11),
    minHeight: verticalScale(44),
    justifyContent: "center",
  },
  firewallControlPrimary: {
    borderColor: "#4f46e5",
    backgroundColor: "#4f46e5",
  },
  firewallControlText: {
    color: "#334155",
    fontSize: normalizeFont(14),
    fontWeight: "800",
  },
  firewallControlTextPrimary: {
    color: "#ffffff",
    fontSize: normalizeFont(14),
    fontWeight: "800",
  },
  firewallGameStateText: {
    color: "#64748b",
    fontSize: normalizeFont(13),
    fontWeight: "700",
  },
  firewallSafeMarker: {
    position: "absolute",
    right: moderateScale(14),
    bottom: moderateScale(8),
    width: scale(40),
    height: verticalScale(4),
    borderRadius: scale(999),
    backgroundColor: "#10b981",
    opacity: 0.12,
  },
  firewallTouchpad: {
    display: "flex",
    gap: moderateScale(8),
    justifyContent: "center",
    marginTop: moderateScale(8),
    flexDirection: "row",
  },
  firewallTouchButton: {
    width: scale(124),
    height: verticalScale(52),
    borderRadius: scale(12),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(10),
    shadowOffset: { width: 0, height: moderateScale(4) },
    elevation: 3,
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
  },
  firewallTouchButtonText: {
    color: colors.text,
    fontSize: normalizeFont(14),
    fontWeight: "800",
  },
  firewallOptionsWrap: {
    gap: moderateScale(8),
  },
  firewallOptionButton: {
    borderRadius: scale(12),
    borderWidth: scale(2),
    borderColor: "#94a3b8",
    backgroundColor: "#ffffff",
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(13),
    minHeight: verticalScale(56),
    justifyContent: "center",
  },
  firewallOptionButtonSelected: {
    borderColor: "#3b82f6",
    backgroundColor: "#dbeafe",
  },
  firewallOptionButtonCorrect: {
    borderColor: "#16a34a",
    backgroundColor: "#dcfce7",
  },
  firewallOptionButtonWrong: {
    borderColor: "#dc2626",
    backgroundColor: "#fee2e2",
  },
  firewallOptionText: {
    color: "#1f2937",
    fontSize: normalizeFont(16),
    fontWeight: "700",
    lineHeight: verticalScale(24),
  },
  firewallSidePanel: {
    width: scale(550),
    gap: moderateScale(10),
    flexDirection: "row",
  },
  firewallSidePanelStacked: {
    width: "100%",
    flexDirection: "column",
  },
  firewallSideCard: {
    borderRadius: scale(14),
    borderWidth: scale(1),
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: moderateScale(12),
    gap: moderateScale(8),
    flex: 1,
  },
  firewallSideTitle: {
    color: colors.text,
    fontSize: normalizeFont(20),
    fontWeight: "800",
  },
  firewallInventoryGrid: {
    gap: moderateScale(6),
  },
  firewallInventoryItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: moderateScale(8),
  },
  firewallInventoryLabel: {
    color: colors.text,
    fontSize: normalizeFont(14),
    fontWeight: "700",
    flex: 1,
  },
  firewallInventoryTag: {
    borderRadius: scale(999),
    borderWidth: scale(1),
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(4),
    fontSize: normalizeFont(12),
    fontWeight: "700",
  },
  firewallInventoryTagSafe: {
    borderColor: "#bbf7d0",
    backgroundColor: "#ecfdf5",
    color: "#065f46",
  },
  firewallInventoryTagLeaked: {
    borderColor: "#fecaca",
    backgroundColor: "#fee2e2",
    color: "#991b1b",
  },
  firewallLegendList: {
    gap: moderateScale(6),
  },
  firewallLegendItem: {
    color: "#12486c",
    fontSize: normalizeFont(14),
    fontWeight: "600",
  },
  firewallLegendTip: {
    color: "#12486c",
    fontSize: normalizeFont(13),
    lineHeight: verticalScale(19),
    fontWeight: "600",
  },
  firewallPauseOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    zIndex: 10,
  },
  firewallPauseModal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: "-50%" }, { translateY: "-50%" }],
    backgroundColor: "#ffffff",
    borderRadius: scale(14),
    padding: moderateScale(20),
    minWidth: scale(300),
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: moderateScale(10),
    shadowOffset: { width: 0, height: moderateScale(4) },
    elevation: 10,
    zIndex: 11,
  },
  firewallPauseTitle: {
    color: colors.text,
    fontSize: normalizeFont(24),
    fontWeight: "800",
    marginBottom: moderateScale(10),
  },
  firewallPauseSubtitle: {
    color: colors.textMuted,
    fontSize: normalizeFont(14),
    fontWeight: "600",
    marginBottom: moderateScale(10),
  },
  firewallGameOverCard: {
    borderRadius: scale(14),
    backgroundColor: "#fef3c7",
    borderWidth: scale(2),
    borderColor: "#fbbf24",
    padding: moderateScale(16),
    marginBottom: moderateScale(16),
    alignItems: "center",
  },
  firewallStatsTitle: {
    color: colors.text,
    fontSize: normalizeFont(20),
    fontWeight: "800",
    marginBottom: moderateScale(12),
  },
  firewallStatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: moderateScale(8),
    borderBottomWidth: scale(1),
    borderBottomColor: "#e5e7eb",
  },
  firewallStatLabel: {
    color: colors.text,
    fontSize: normalizeFont(14),
    fontWeight: "600",
  },
  firewallStatValue: {
    color: "#3b82f6",
    fontSize: normalizeFont(16),
    fontWeight: "800",
  },
  firewallComboDisplay: {
    position: "absolute",
    top: moderateScale(20),
    right: moderateScale(20),
    backgroundColor: "#fbbf24",
    borderRadius: scale(12),
    padding: moderateScale(12),
    gap: moderateScale(8),
    zIndex: 5,
    shadowColor: "#d97706",
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(8),
    shadowOffset: { width: 0, height: moderateScale(2) },
    elevation: 4,
  },
  firewallComboNumber: {
    color: "#78350f",
    fontSize: normalizeFont(28),
    fontWeight: "800",
  },
  firewallComboLabel: {
    color: "#78350f",
    fontSize: normalizeFont(12),
    fontWeight: "700",
  },
  firewallMultiplierBadge: {
    backgroundColor: "#fb923c",
    borderRadius: scale(6),
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(4),
  },
  firewallActiveEffectBox: {
    position: "absolute",
    top: moderateScale(20),
    left: moderateScale(20),
    borderRadius: scale(10),
    borderWidth: scale(2),
    borderColor: "#10b981",
    backgroundColor: "#ecfdf5",
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(8),
    zIndex: 5,
    shadowColor: "#059669",
    shadowOpacity: 0.15,
    shadowRadius: moderateScale(6),
    shadowOffset: { width: 0, height: moderateScale(2) },
    elevation: 3,
  },
  firewallEffectLabel: {
    color: "#065f46",
    fontSize: normalizeFont(13),
    fontWeight: "700",
  },
  firewallEffectTime: {
    color: "#10b981",
    fontSize: normalizeFont(12),
    fontWeight: "600",
  },
});
