import { StyleSheet } from "react-native";
import {
    moderateScale,
    normalizeFont,
    scale,
    verticalScale,
} from "../../../lib/responsive";
import { colors } from "../../../theme/colors";

export const quizClassicStyles = StyleSheet.create({
  questionCard: {
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: moderateScale(14),
    gap: moderateScale(12),
  },
  questionEventCard: {
    borderRadius: scale(14),
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    padding: moderateScale(12),
    gap: moderateScale(10),
  },
  questionEventHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(10),
  },
  questionEventIconWrap: {
    width: scale(42),
    height: scale(42),
    borderRadius: scale(12),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e0e7ff",
  },
  questionEventIcon: {
    fontSize: normalizeFont(20),
  },
  questionEventTitle: {
    flex: 1,
    color: "#1e293b",
    fontSize: normalizeFont(18),
    fontWeight: "800",
  },
  questionEventContext: {
    color: "#334155",
    fontSize: normalizeFont(14),
    lineHeight: verticalScale(21),
    fontWeight: "600",
  },
  questionEventMessageBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#eef2f7",
    padding: moderateScale(12),
  },
  questionEventMessage: {
    color: "#374151",
    fontSize: normalizeFont(14),
    lineHeight: verticalScale(22),
    fontWeight: "600",
  },
  questionTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  questionMeta: {
    color: colors.textMuted,
    fontSize: normalizeFont(12),
    fontWeight: "700",
    letterSpacing: moderateScale(0.4),
  },
  optionsWrap: {
    gap: moderateScale(8),
  },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(10),
    borderRadius: scale(12),
    borderWidth: scale(2),
    borderColor: "#e5e7eb",
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(11),
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  optionItemSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: "#1e3a8a",
    shadowColor: colors.accent,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionItemCorrect: {
    borderColor: "#22c55e",
    borderWidth: 3,
    backgroundColor: "#166534",
    shadowColor: "#22c55e",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionItemWrong: {
    borderColor: "#ef4444",
    borderWidth: 3,
    backgroundColor: "#7f1d1d",
    shadowColor: "#ef4444",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionIndex: {
    width: scale(24),
    height: scale(24),
    borderRadius: scale(999),
    borderWidth: scale(2),
    borderColor: "#d1d5db",
    color: "#4b5563",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: normalizeFont(12),
    fontWeight: "800",
  },
  optionIndexSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    color: "#ffffff",
    backgroundColor: colors.accent,
  },
  optionIndexCorrect: {
    borderColor: "#22c55e",
    borderWidth: 3,
    color: "#ffffff",
    backgroundColor: "#22c55e",
  },
  optionIndexWrong: {
    borderColor: "#ef4444",
    borderWidth: 3,
    color: "#ffffff",
    backgroundColor: "#ef4444",
  },
  optionText: {
    flex: 1,
    color: colors.text,
    fontSize: normalizeFont(14),
    lineHeight: verticalScale(19),
  },
  optionTextSelected: {
    color: "#ffffff",
    fontWeight: "700",
  },
  feedbackCard: {
    borderRadius: scale(12),
    borderWidth: scale(2),
    padding: moderateScale(12),
    gap: moderateScale(6),
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  feedbackCardSuccess: {
    borderColor: "#22c55e",
    backgroundColor: "#166534",
  },
  feedbackCardError: {
    borderColor: "#ef4444",
    backgroundColor: "#7f1d1d",
  },
  feedbackTitle: {
    color: "#ffffff",
    fontSize: normalizeFont(13),
    fontWeight: "800",
    letterSpacing: moderateScale(0.2),
  },
  feedbackBody: {
    color: "#e8f5e9",
    fontSize: normalizeFont(13),
    lineHeight: verticalScale(19),
  },
  timeWarningCard: {
    borderRadius: scale(10),
    borderWidth: scale(2),
    borderColor: "#fbbf24",
    backgroundColor: "#78350f",
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(8),
    shadowColor: "#fbbf24",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  timeWarningText: {
    color: "#fef3c7",
    fontSize: normalizeFont(12),
    fontWeight: "800",
    lineHeight: verticalScale(18),
  },
});
